name: Sync Gist
on: [push]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch gist file
        run: |
          curl -L "https://gist.githubusercontent.com/seinecle/689a53bceca96147a04e93bdc5f83940/raw/file-list-of-ai-apps-for-visual-creation.md" \
            -o _includes/file-list-of-ai-apps-for-visual-creation.md
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add _includesgist-list-of-ai-apps-for-visual-creation.md
          git commit -m "Sync gist" || echo "No changes"
          git push
